<?php

namespace TSTeam;

if (!defined('ABSPATH')) {
    exit;
}

class Strings {

    public static function get_translated_strings() {
        return array(
            // Existing strings
            'dashboard'              => __('Dashboard', 'ts-team-member'),
            'team_showcase'          => __('Team Showcase', 'ts-team-member'),
            'team_member'            => __('Team Member', 'ts-team-member'),
            'member_category'        => __('Member Category', 'ts-team-member'),
            'tools'                  => __('Tools', 'ts-team-member'),
            'account'                => __('Account', 'ts-team-member'),
            'support_forum'          => __('Support', 'ts-team-member'),
            'get_pro'                => __('Get Pro', 'ts-team-member'),
            'grab_your_discount'     => __('Grab Your Discount', 'ts-team-member'),
            'upgrade_to_pro'         => __('Upgrade to Pro', 'ts-team-member'),
            'documentations'         => __('Documentations', 'ts-team-member'),
            'help_and_support'       => __('Help & Support', 'ts-team-member'),
            'video_guide'            => __('Video Guide', 'ts-team-member'),
            'add'                    => __('Add', 'ts-team-member'),
            'create'                 => __('Create', 'ts-team-member'),
            'select'                 => __('Select', 'ts-team-member'),
            'settings'               => __('Tools', 'ts-team-member'),
            'update'                 => __('Update', 'ts-team-member'),
            'publish'                => __('Publish', 'ts-team-member'),
            'title'                  => __('Title', 'ts-team-member'),
            'shortcode'              => __('Shortcode', 'ts-team-member'),
            'snippet'                => __('Snippet', 'ts-team-member'),
            'action'                 => __('Action', 'ts-team-member'),
            'edit'                   => __('Edit', 'ts-team-member'),
            'edit_design'            => __('Edit Design', 'ts-team-member'),
            'delete'                 => __('Delete', 'ts-team-member'),
            'image'                  => __('Image', 'ts-team-member'),
            'name'                   => __('Name', 'ts-team-member'),
            'designation'            => __('Designation', 'ts-team-member'),
            'description'            => __('Description', 'ts-team-member'),
            'basic_information'      => __('Basic Information', 'ts-team-member'),
            'member_name'            => __('Member Name', 'ts-team-member'),
            'member_designation'     => __('Member Designation', 'ts-team-member'),
            'member_email'           => __('Member Email', 'ts-team-member'),
            'member_mobile'          => __('Member Mobile', 'ts-team-member'),
            'member_description'     => __('Member Description', 'ts-team-member'),
            'member_image'           => __('Member Image', 'ts-team-member'),
            'details_information'    => __('Details Information', 'ts-team-member'),
            'member_telephone'       => __('Member Telephone', 'ts-team-member'),
            'years_of_experience'    => __('Years of Experience', 'ts-team-member'),
            'company'                => __('Company', 'ts-team-member'),
            'location'               => __('Location', 'ts-team-member'),
            'profile_links'          => __('Profile Links', 'ts-team-member'),
            'website'                => __('Website', 'ts-team-member'),
            'resume_link'            => __('Resume Link', 'ts-team-member'),
            'hire_link'              => __('Hire Link', 'ts-team-member'),
            'donation_link'          => __('Donation Link', 'ts-team-member'),
            'social_links'           => __('Social Links', 'ts-team-member'),
            'skills'                 => __('Skills', 'ts-team-member'),
            'showcase_name'          => __('Showcase Name', 'ts-team-member'),
            'content'                => __('Content', 'ts-team-member'),
            'loading_editor'         => __('Loading Editor', 'ts-team-member'),
            'copy_design'            => __('Copy Design', 'ts-team-member'),
            'paste_design'           => __('Paste Design', 'ts-team-member'),
            'view_style'             => __('View Style', 'ts-team-member'),
            'layout'                 => __('Layout', 'ts-team-member'),
            'details_style'          => __('Details Style', 'ts-team-member'),
            'container_width'        => __('Container Width', 'ts-team-member'),
            'columns'                => __('Columns', 'ts-team-member'),
            'column_gap'             => __('Column Gap', 'ts-team-member'),
            'style'                  => __('Style', 'ts-team-member'),
            'common_styles'          => __('Common Styles', 'ts-team-member'),
            'background_color'       => __('Background Color', 'ts-team-member'),
            'member_name_color'      => __('Member Name Color', 'ts-team-member'),
            'member_designation_color' => __('Member Designation Color', 'ts-team-member'),
            'member_description_color' => __('Member Description Color', 'ts-team-member'),
            'border_color'           => __('Border Color', 'ts-team-member'),
            'image_border_color'     => __('Image Border Color', 'ts-team-member'),
            'border_width'           => __('Border Width', 'ts-team-member'),
            'border_radius'          => __('Border Radius', 'ts-team-member'),
            'image_border_width'     => __('Image Border Width', 'ts-team-member'),
            'image_border_radius'    => __('Image Border Radius', 'ts-team-member'),
            'font'                   => __('Font', 'ts-team-member'),
            'name_typography'        => __('Name Typography', 'ts-team-member'),
            'designation_typography' => __('Designation Typography', 'ts-team-member'),
            'description_typography' => __('Description Typography', 'ts-team-member'),
            'details_typography'     => __('Details Typography', 'ts-team-member'),
            'social'                 => __('Social', 'ts-team-member'),
            'social_icon_border_radius' => __('Social Icon Border Radius', 'ts-team-member'),
            'social_icon_color'      => __('Social Icon Color', 'ts-team-member'),
            'social_icon_background_color' => __('Social Icon Background Color', 'ts-team-member'),
            'motion'                 => __('Motion', 'ts-team-member'),
            'hover_animation'        => __('Hover Animation', 'ts-team-member'),
            'global'                 => __('Global', 'ts-team-member'),
            'container_background_color' => __('Container Background Color', 'ts-team-member'),
            'container_margin'       => __('Container Margin', 'ts-team-member'),
            'container_padding'      => __('Container Padding', 'ts-team-member'),
            'container_border_radius'=> __('Container Border Radius', 'ts-team-member'),
            'successfully_updated'   => __('Successfully Updated', 'ts-team-member'),
            'settings_updated_message' => __('The settings have been successfully updated.', 'ts-team-member'),
            'are_you_sure'           => __('Are you sure?', 'ts-team-member'),
            'delete_confirmation'    => __("You're going to delete this", 'ts-team-member'),
            'no_keep_it'             => __('No, Keep it.', 'ts-team-member'),
            'yes_delete'             => __('Yes, Delete!', 'ts-team-member'),
        );
    }
}