export const googleFonts = [
    { label: 'Dancing Script', value: 'Dancing+Script' },
    { label: 'Pacifico', value: 'Pacifico' },
    { label: 'Shadows Into Light', value: 'Shadows+Into+Light' },
    { label: 'Great Vibes', value: 'Great+Vibes' },
    { label: 'Satisfy', value: 'Satisfy' },
    { label: 'Caveat', value: 'Caveat' },
    { label: 'Courgette', value: 'Courgette' },
    { label: 'Kaushan Script', value: 'Kaushan+Script' },
    { label: 'Sacramento', value: 'Sacramento' },
    { label: 'Indie Flower', value: 'Indie+Flower' },
    { label: 'Merriweather', value: 'Merriweather' },
    { label: 'Playfair Display', value: 'Playfair+Display' },
    { label: 'Lora', value: 'Lora' },
    { label: 'Crimson Pro', value: 'Crimson+Pro' },
    { label: 'Slabo 27px', value: 'Slabo+27px' },
    { label: 'Bitter', value: 'Bitter' },
    { label: 'EB Garamond', value: 'EB+Garamond' },
    { label: 'Cormorant Garamond', value: 'Cormorant+Garamond' },
    { label: 'Spectral', value: 'Spectral' },
    { label: 'Cardo', value: 'Cardo' },
    { label: 'Roboto', value: 'Roboto' },
    { label: 'Open Sans', value: 'Open+Sans' },
    { label: 'Poppins', value: 'Poppins' },
    { label: 'Lato', value: 'Lato' },
    { label: 'Montserrat', value: 'Montserrat' },
    { label: 'Nunito', value: 'Nunito' },
    { label: 'Work Sans', value: 'Work+Sans' },
    { label: 'Raleway', value: 'Raleway' },
    { label: 'Inter', value: 'Inter' },
    { label: 'Ubuntu', value: 'Ubuntu' },
    { label: 'Oswald', value: 'Oswald' },
    { label: 'Righteous', value: 'Righteous' },
    { label: 'Cinzel', value: 'Cinzel' },
    { label: 'Anton', value: 'Anton' },
    { label: 'Abril Fatface', value: 'Abril+Fatface' },
    { label: 'Bebas Neue', value: 'Bebas+Neue' },
    { label: 'Alfa Slab One', value: 'Alfa+Slab+One' },
    { label: 'Lobster', value: 'Lobster' },
    { label: 'Quicksand', value: 'Quicksand' },
    { label: 'Patua One', value: 'Patua+One' },
    { label: 'Inconsolata', value: 'Inconsolata' },
    { label: 'Roboto Mono', value: 'Roboto+Mono' },
    { label: 'Source Code Pro', value: 'Source+Code+Pro' },
    { label: 'Fira Code', value: 'Fira+Code' },
    { label: 'Space Mono', value: 'Space+Mono' },
    { label: 'VT323', value: 'VT323' },
    { label: 'JetBrains Mono', value: 'JetBrains+Mono' },
    { label: 'Anonymous Pro', value: 'Anonymous+Pro' },
    { label: 'IBM Plex Mono', value: 'IBM+Plex+Mono' },
    { label: 'Courier Prime', value: 'Courier+Prime' },
];