export const googleFonts = [
    { label: 'Dancing Script', value: 'Dancing+Script:wght@400;700' },
    { label: 'Pacifico', value: 'Pacifico' },
    { label: 'Shadows Into Light', value: 'Shadows+Into+Light' },
    { label: 'Great Vibes', value: 'Great+Vibes' },
    { label: 'Satisfy', value: 'Satisfy' },
    { label: 'Caveat', value: 'Caveat:wght@400;700' },
    { label: 'Courgette', value: 'Courgette' },
    { label: 'Kaushan Script', value: 'Kaushan+Script' },
    { label: 'Sacramento', value: 'Sacramento' },
    { label: 'Indie Flower', value: 'Indie+Flower' },
    { label: 'Merriweather', value: 'Merriweather:wght@400;700' },
    { label: 'Playfair Display', value: 'Playfair+Display:wght@400;700' },
    { label: 'Lora', value: 'Lora:wght@400;700' },
    { label: 'Crimson Pro', value: 'Crimson+Pro:wght@400;700' },
    { label: 'Slabo 27px', value: 'Slabo+27px' },
    { label: 'Bitter', value: 'Bitter:wght@400;700' },
    { label: 'EB Garamond', value: 'EB+Garamond:wght@400;700' },
    { label: 'Cormorant Garamond', value: 'Cormorant+Garamond:wght@400;700' },
    { label: 'Spectral', value: 'Spectral:wght@400;700' },
    { label: 'Cardo', value: 'Cardo:wght@400;700' },
    { label: 'Roboto', value: 'Roboto:wght@400;700' },
    { label: 'Open Sans', value: 'Open+Sans:wght@400;700' },
    { label: 'Poppins', value: 'Poppins:wght@400;700' },
    { label: 'Lato', value: 'Lato:wght@400;700' },
    { label: 'Montserrat', value: 'Montserrat:wght@400;700' },
    { label: 'Nunito', value: 'Nunito:wght@400;700' },
    { label: 'Work Sans', value: 'Work+Sans:wght@400;700' },
    { label: 'Raleway', value: 'Raleway:wght@400;700' },
    { label: 'Inter', value: 'Inter:wght@400;700' },
    { label: 'Ubuntu', value: 'Ubuntu:wght@400;700' },
    { label: 'Oswald', value: 'Oswald:wght@400;700' },
    { label: 'Righteous', value: 'Righteous' },
    { label: 'Cinzel', value: 'Cinzel:wght@400;700' },
    { label: 'Anton', value: 'Anton' },
    { label: 'Abril Fatface', value: 'Abril+Fatface' },
    { label: 'Bebas Neue', value: 'Bebas+Neue' },
    { label: 'Alfa Slab One', value: 'Alfa+Slab+One' },
    { label: 'Lobster', value: 'Lobster' },
    { label: 'Quicksand', value: 'Quicksand:wght@400;700' },
    { label: 'Patua One', value: 'Patua+One' },
    { label: 'Inconsolata', value: 'Inconsolata:wght@400;700' },
    { label: 'Roboto Mono', value: 'Roboto+Mono:wght@400;700' },
    { label: 'Source Code Pro', value: 'Source+Code+Pro:wght@400;700' },
    { label: 'Fira Code', value: 'Fira+Code:wght@400;700' },
    { label: 'Space Mono', value: 'Space+Mono:wght@400;700' },
    { label: 'VT323', value: 'VT323' },
    { label: 'JetBrains Mono', value: 'JetBrains+Mono:wght@400;700' },
    { label: 'Anonymous Pro', value: 'Anonymous+Pro:wght@400;700' },
    { label: 'IBM Plex Mono', value: 'IBM+Plex+Mono:wght@400;700' },
    { label: 'Courier Prime', value: 'Courier+Prime:wght@400;700' },
  ];  